[package]
name = "torc_statesync"
version = "0.1.0"
authors = ["jmu"]


[dependencies]
hyper = ">= 0.6.8"
rustc-serialize = ">= 0.3.15"
url = ">= 0.2.37"
iron = "*"
serde = "*"
serde_json ="*"

router = "*"
urlencoded = "*"
quasi = "0.3.6"
