[package]
name = "etcdclient"
version = "0.1.0"
authors = ["jmu"]


[dependencies]
iron = "*"
serde = "*"
serde_json ="*"
serde_macros = "*"
router = "*"
urlencoded = "*"
hyper = ">= 0.6.8"


[dependencies.rust_etcd]
path = "../rust_etcd"
version = "0.2.0"
